cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/purchases/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/purchases/<int:product_id>/',
        views.cart_remove,
        name='cart_remove'
    ),
    path('export/', views.cart_export, name='cart_export'),
]

foodgram/urls.py
from cart.views import PurchasesView, cart_detail
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import include, path
from ingredients.views import Ingredients
from recipes import views
from users.views import follows, index, user_profile

handler404 = 'recipes.views.handler404'


urlpatterns = [
	
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path('users/<int:id>/', user_profile, name='user_profile'),

    path('cart/', include('cart.urls', namespace='cart')),

    path('recipes/', include('recipes.urls', namespace='recipes')),

    path('ingredients/', Ingredients.as_view(), name='ingredients'),

    path('purchases/', PurchasesView.as_view(), name='purchases'),
    path('purchases/<int:id>/', PurchasesView.as_view(), name='purchases_add'),

    path(
        'subscriptions',
        views.SubscriptionsView.as_view(),
        name='subscriptions_add'
    ),
    path(
        'subscriptions/<int:id>/',
        views.SubscriptionsView.as_view(),
        name='subscriptions_delete'
    ),

    path('favourites/', views.FavouritesView.as_view(), name='favourites'),
    path(
        'favorites/<int:id>',
        views.FavouritesView.as_view(),
        name='favorites'
    ),

    path('new/', views.new, name='new'),

    path('follows/', follows, name='follows'),

    path('shoplist', cart_detail, name='shoplist'),
    ]

urlpatterns += [
    path(
        'about-us/',
        flatpages_views.flatpage,
        {'url': 'about-us/'}, name='about'
    ),
    path(
        'about-author/',
        flatpages_views.flatpage,
        {'url': 'about-author/'},
        name='author'
    ),
    path(
        'about-spec/',
        flatpages_views.flatpage,
        {'url': 'about-spec/'}, name='spec'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

recipes/urls.py
from django.urls import path
from . import views


app_name = 'recipes'

urlpatterns = [
    path('<int:id>', views.recipe_detail, name='recipe_detail'),
    path('<int:id>/edit', views.recipe_change, name='recipe_change'),
    path('<int:id>/terminate', views.recipe_delete, name='recipe_delete'),
]

users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
        path("signup/", views.SignUp.as_view(), name="signup"),
]

recipes/models.py
from django.db import models
from ingredients.models import Ingredient
from django.contrib.auth.models import User


class Tag(models.Model):
    tag_name = models.CharField('Name', max_length=20, null=True)
    tag_name_eng = models.CharField('Name_eng', max_length=20, null=True, blank=True)
    value = models.CharField('Value', max_length=64)
    style = models.CharField('Style', max_length=64, null=True)

    def __str__(self):
        return self.tag_name


class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(blank=True)

    def __str__(self):
        return self.ingredient.name


class Recipe(models.Model):
    title = models.CharField(max_length=64)
    author = models.ForeignKey(
        User,
        related_name="user_recipes",
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='recipes/', blank=True)
    description = models.TextField()
    ingredients = models.ManyToManyField(RecipeIngredient)
    tag = models.ManyToManyField(Tag)
    cooking_duration = models.IntegerField()
    slug = models.SlugField(unique=True)
    created = models.DateTimeField(auto_now_add=True)
    favourite = models.ManyToManyField(
        User,
        related_name="user_favourites",
        blank=True
    )

    def __str__(self):
        return self.title

    @property
    def taglist(self):
        return list(self.tag.all())

    @property
    def ingredientlist(self):
        return list(self.ingredients.all())

    class Meta:
        ordering = ('-created', )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="user_followers"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="user_followings"
    )

recipes/forms.py
from django.forms import ModelForm
from recipes.models import Ingredient, Recipe


class IngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = ("name", "units")


class RecipeForm(ModelForm):

    class Meta:
        model = Recipe
        fields = ("title", "tag", 'cooking_duration', 'description', 'image')

recipes/views.py
import json

from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import View
from ingredients.views import get_ingredients

from cart.utils import get_cart_ids
from recipes.models import Follow, Recipe

from .forms import RecipeForm
from .utils import get_filters, get_tags, unique_slug_generator


def new(request):
    if request.method == 'POST':
        ingredients = get_ingredients(request)
        tags = get_tags(request)
        form = RecipeForm(request.POST, files=request.FILES or None)

        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.slug = unique_slug_generator(recipe)
            recipe.save()
            for tag in tags:
                recipe.tag.add(tag)
            for item in ingredients:
                recipe.ingredients.add(item.id)
            return redirect('index')
    else:
        form = RecipeForm()
        tags = {'Завтрак': 'Завтрак', 'Обед': 'Обед', 'Ужин': 'Ужин'}
    return render(request, 'formRecipe.html', {'form': form, 'tags': tags})


def recipe_delete(request, id):
    recipe = get_object_or_404(Recipe, id=id)
    recipe.delete()
    return redirect('index')


def recipe_change(request, id):
    recipe = get_object_or_404(Recipe, id=id)

    if request.method == 'POST':
        ingredients = get_ingredients(request)
        tags = get_tags(request)
        form = RecipeForm(
            request.POST,
            instance=recipe,
            files=request.FILES or None
        )
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            recipe.tag.clear()
            recipe.ingredients.clear()

            for tag in tags:
                recipe.tag.add(tag)
            for item in ingredients:
                recipe.ingredients.add(item)
            return redirect('index')

    tags = [tag.id for tag in recipe.taglist]
    ingredients = recipe.ingredientlist
    form = RecipeForm(instance=recipe)
    return render(
        request,
        'formChangeRecipe.html',
        {
            'form': form,
            'recipe': recipe,
            'tags': tags,
            'ingredients': ingredients
        }
    )


def recipe_detail(request, id):
    recipe = get_object_or_404(Recipe, id=id)
    return render(
        request,
        'singlePage.html',
        {'recipe': recipe}
    )


class FavouritesView(View):
    http_method_names = ['get', 'post', 'delete']

    def get(self, request):
        user = request.user
        filters = get_filters(request)
        tag_names = [k for k, v in filters.items() if v == 'checked']
        cart_ids = get_cart_ids(request)
        recipes = user.user_favourites.filter(
            tag__tag_name_eng__in=tag_names).distinct()
        paginator = Paginator(recipes, 6)
        page_number = request.GET.get('page')
        page = paginator.get_page(page_number)
        request.GET.clear()

        context = {
            'cart_ids': cart_ids,
            'filters': filters,
            'recipes': page,
            'paginator': paginator
            }
        return render(request, 'favorite.html', context)

    def post(self, request, id):
        recipe = get_object_or_404(Recipe, id=id)
        recipe.favourite.add(request.user)
        return JsonResponse({'success': True})

    def delete(self, request, id):
        recipe = get_object_or_404(Recipe, id=id)
        recipe.favourite.remove(request.user)
        return JsonResponse({'success': True})


class SubscriptionsView(View):
    def post(self, request):
        id = json.loads(request.body)['id']
        user = request.user
        author = get_object_or_404(User, id=id)
        follow = Follow.objects.get_or_create(user=user, author=author)
        return JsonResponse({'success': True})

    def delete(self, request, id):
        user = request.user
        author = get_object_or_404(User, id=id)
        follow = get_object_or_404(Follow, user=user, author=author).delete()
        return JsonResponse({'success': True})


def handler404(request, exception):
    return render(request, "404.html", {"path": request.path}, status=404)

templates/authForm.html
{% extends "indexAuth.html" %}
{% load static %}
{% block title %}Войти на сайт{% endblock %}
	{% block maintitle %}Войти на сайт{% endblock %}
	{% block style %}"{% static 'pages/form.css' %}"{% endblock %}
	{% block content %}
    <div class="form-container">
        <form class="form" method="post"> 
            <div class="form__group">
                <label for="id_username" class="form__label">Имя</label>
                <div class="form__field-group">
                    <input type="text" name="username" id="id_username" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_password" class="form__label">Пароль</label>
                <div class="form__field-group">
                    <input type="password" name="password" id="id_password" class="form__input">
                    <span class="form__error">Имя пользователя и пароль не совпадают. Введите правильные данные.</span>
                </div>
            </div>
            <div class="form__footer">
                {% csrf_token %}
                <button class="button button_style_blue" name="login" value="Log In">Войти</button>
                <a class="form__forgot-link">Забыли пароль?</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/authorRecipe.html
{% extends "indexAuth.html" %}
{% load static %}
{% block title %}Рецепты{% endblock %}
	{% block maintitle %}{{ author.username }}{% endblock %}
	{% block style %}"{% static 'pages/index.css' %}"{% endblock %}
	{% block content %}
        <div class="author-subscribe" data-author={{ author.id }}>
            {% csrf_token %}
            <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" 
                {% if follow.author != author %}data-out>Подписаться на автора{% else %}>Отписаться от автора{% endif %}</button></p>
        </div>
        {% include "card.html" with cart_ids=cart_ids recipes=recipes %} 
        {% endblock %}
		{% block script %}
  <script src="{% static '/js/utils/filters.js' %}"></script>
  <script src="{% static '/js/components/MainCards.js' %}"></script>
 
  <script src="{% static '/js/components/Purchases.js' %}"></script>
  <script src="{% static '/js/components/Favorites.js' %}"></script>
  <script src="{% static '/js/components/Subscribe.js' %}"></script>

  <script src="{% static '/js/config/config.js' %}"></script>
  <script src="{% static '/js/components/AuthorRecipe.js' %}"></script>
  <script src="{% static '/js/components/Header.js' %}"></script>

  <script src="{% static '/js/api/Api.js' %}"></script>
  <script src="{% static 'authorRecipe.js' %}"></script>
  {% endblock %}

templates/card.html
{% load static %}
{% load user_filters %}
{% load thumbnail %}
<div class="card-list">
{% for item in recipes %}
	<div class="card" data-id={{ item.id }}>
		{% thumbnail item.image "350x250" crop="center" upscale=True as im %}
		<a href="{% url 'recipes:recipe_detail' item.id %}" class="link">{% if item.image %}<img src="{{ im.url }}">
		{% endif %}</a>
		{% endthumbnail %}
		<div class="card__body">
			<a class="card__title link" href="{% url 'recipes:recipe_detail' item.id %}">{{ item.title }}</a>
			<ul class="card__items">
				{% include "tags.html" with tags=item.taglist %}  
			</ul>
			<div class="card__items card__items_column">
				<p class="card__text"><span class="icon-time"></span>{{ item.cooking_duration }} мин.</p>
				<p class="card__text"><span class="icon-user"></span> <a href="{% url 'user_profile' item.author.id %}" style="color: black">{{ item.author }}</a></p>
			</div>
		</div>
		<div class="card__footer">
			{% csrf_token %}
			<button class="button button_style_light-blue" name="purchases" 
			{% if item.id not in cart_ids %}data-out><span class="icon-plus button__icon"></span>Добавить в покупки
			{% else %}><span class="icon-check button__icon"></span>Рецепт добавлен{% endif %}</button>
			<button class="button button_style_none" name="favorites" 
			{% if item.id|is_favorite:request.user %}><span class="icon-favorite icon-favorite_active"></span>
			{% else %}data-out><span class="icon-favorite"></span>{% endif %}</button>
		</div>
	</div>
{% endfor %}
</div>

templates/changePassword.html
{% extends "indexAuth.html" %}
{% load static %}
{% block title %}Изменить пароль{% endblock %}
	{% block maintitle %}Изменить пароль{% endblock %}
	{% block style %}"{% static 'pages/index.css' %}"{% endblock %}
	{% block content %}
    <div class="form-container">
        <form class="form">
            <div class="form__group">
                <label for="id_oldPassword" class="form__label">Старый пароль</label>
                <div class="form__field-group">
                    <input type="text" name="old_password" id="id_oldPassword" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_newPassword" class="form__label">Новый пароль</label>
                <div class="form__field-group">
                    <input type="password" name="new_password" id="id_newPassword" class="form__input">
                    <span class="form__input-info">Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</span>
                    <span class="form__input-info">Ваш пароль должен содержать как минимум 8 символов.</span>
                    <span class="form__input-info">Ваш пароль не может быть одним из широко распространённых паролей.</span>
                    <span class="form__input-info">Ваш пароль не может состоять только из цифр.</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_confirmPassword" class="form__label">Подтверждение нового пароля</label>
                <div class="form__field-group">
                    <input type="password" name="confirm_password" id="id_confirmPassword" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
                <div class="form__footer">
                    <button class="button button_style_blue">Изменить пароль</button>
                </div>
        </form>
    </div>
	{% endblock %}

templates/filters.html
{% if filters %}
<ul class="tags">
	<li class="tags__item">
		<input
							type="checkbox"
							name="tag_cb"
							value="{{ tag_id }}"
							id="breakfast"
							onclick="onClickHandler()"
							class="tags__checkbox tags__checkbox_style_orange" 
							{{ filters.breakfast }}>
							<label for="dinner" class="tags__label">Завтрак</label>
	</li>
	<li class="tags__item">
		<input
							type="checkbox"
							name="tag_cb"
							value="{{ tag_id }}"
							id="lunch"
							onclick="onClickHandler()"
							class="tags__checkbox tags__checkbox_style_green" 
							{{ filters.lunch }}>
							<label for="dinner" class="tags__label">Обед</label>
	</li>
	<li class="tags__item">
		<input
							type="checkbox"
							name="tag_cb"
							value="{{ tag_id }}"
							id="dinner"
							onclick="onClickHandler()"
							class="tags__checkbox tags__checkbox_style_purple" 
							{{ filters.dinner }}>
							<label for="dinner" class="tags__label">Ужин</label>
	</li>
	
</ul>
{% endif %}

templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'about' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'spec' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/header.html
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            {% with total_items=cart|length %}
            {% if user.is_authenticated %}
            <ul class="nav__items list">

				<li class={% if request.resolver_match.url_name == 'index' %} 'nav__item nav__item_active' {% else %} 'nav__item' {% endif %}>
					<a href={% url 'index' %} class="nav__link link">Рецепты</a></li>
				<li class={% if request.resolver_match.url_name == 'follows' %} 'nav__item nav__item_active' {% else %} 'nav__item' {% endif %}>
					<a href="{% url 'follows'%}" class="nav__link link">Мои подписки</a></li>
				<li class={% if request.resolver_match.url_name == 'new' %} 'nav__item nav__item_active' {% else %} 'nav__item' {% endif %}>
					<a href="{% url 'new'%}" class="nav__link link">Создать рецепт</a></li>
				<li class={% if request.resolver_match.url_name == 'favourites' %} 'nav__item nav__item_active' {% else %} 'nav__item' {% endif %}>
					<a href="{% url 'favourites'%}" class="nav__link link">Избранное</a></li>
				<li class={% if request.resolver_match.url_name == 'purchases' %} 'nav__item nav__item_active' {% else %} 'nav__item' {% endif %}>
					<a href="{% url 'purchases'%}" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter">{{ total_items }}</span></li>

            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                <li class="nav__item"><a href="{% url 'logout' %}"  class="nav__link link">Выход</a></li>
            </ul>
            {% else %}
            <ul class="nav__items list">
                <li class="nav__item nav__item_active"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                <li class="nav__item nav__item_disabled"><a href="{% url 'purchases' %}" class="nav__link link">Список покупок <span class="badge badge_style_blue nav__badge" id="counter">{{ total_items }}</span></a></li>
            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="{% url 'users:signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
            </ul>
            {% endif %}
            {% endwith %}
        </div>
    </nav>
</header>

templates/myFollow.html
{% extends "indexAuth.html" %}
{% load static %}
{% load thumbnail %}
	{% block title %}Мои подписки{% endblock %}
	{% block maintitle %}Мои подписки{% endblock %}
	{% block style %}"{% static 'pages/myFollow.css' %}"{% endblock %}
	{% block content %}
    
    <div class="card-list">
        {% for author in authors %}
        <div class="card-user" data-id="{{ author.id }}">
            <div class="card-user__header">
                <h2 class="card-user__title">"{{ author.username }}"</h2>
            </div>
            <div class="card-user__body">
                <ul class="card-user__items">
                    {% for recipe in author.user_recipes.all %}
                    {% thumbnail recipe.image "50x50" crop="center" upscale=True as im %}
                    <li class="card-user__item">
                        <div class="recipe">
                            <img src="{{ im.url }}" alt="какой-то-текст" class="recipe__image">
                            <h3 class="recipe__title">"{{ recipe.title }}"</h3>
                            <p class="recipe__text"><span class="icon-time"></span>"{{ recipe.cooking_duration}} мин."</p>
                        </div>
                    </li>
                    {% endthumbnail %}
                    {% endfor %}
                    <li class="card-user__item">
                        <a href="{% url 'user_profile' author.id %}" class="card-user__link link">Еще рецепты автора...</a>
                    </li>
                </ul>
            </div>
            <div class="card-user__footer">
                {% csrf_token %}
                <button class="button button_style_light-blue button_size_auto" name="subscribe" data-out>Отписаться</button>
            </div>
        </div>
        {% endfor %}
    </div>
	
	{% endblock %}
	{% if authors.has_other_pages %}
        {% include "pagination.html" with page=authors paginator=paginator%}
	{% endif %}
    {% block script %}
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/MyFollow.js' %}"></script>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'myFollow.js' %}"></script>
{% endblock %}

templates/nav.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
            {% if page.has_previous %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ page.previous_page_number }}"><span class="icon-left"></span></a></li>
            {% else %}
                
            {% endif %}
            {% for i in paginator.page_range %}
                    {% if page.number == i %}
                    <li class="pagination__item pagination__item_active"><a class="pagination__link link">{{ i }}</a></li>
                    {% else %}
                    <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
            {% endfor %}
            {% if page.has_next %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ page.next_page_number }}"><span class="icon-right"></span></a></li>
            {% endif %}
    </ul>
</nav>

templates/pagination.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
            {% if page.has_previous %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ page.previous_page_number }}"><span class="icon-left"></span></a></li>
            {% else %}
                
            {% endif %}
            {% for i in paginator.page_range %}
                    {% if page.number == i %}
                    <li class="pagination__item pagination__item_active"><a class="pagination__link link">{{ i }}</a></li>
                    {% else %}
                    <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
            {% endfor %}
            {% if page.has_next %}
            <li class="pagination__item"><a class="pagination__link link" href="?page={{ page.next_page_number }}"><span class="icon-right"></span></a></li>
            {% endif %}
    </ul>
</nav>

templates/reg.html
{% extends "indexAuth.html" %}
{% load static %}
{% block title %}Регистрация{% endblock %}
	{% block maintitle %}Регистрация{% endblock %}
	{% block style %}"{% static 'pages/form.css' %}"{% endblock %}
	{% block content %}
    <div class="form-container">
        <form class="form" action="." method="post">
            <div class="form__group">
                <label for="id_first_name" class="form__label">Имя</label>
                <div class="form__field-group">
                    <input type="text" name="first_name" id="id_first_name" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_username" class="form__label">Имя пользователя</label>
                <div class="form__field-group">
                    <input type="text" name="username" id="id_username" class="form__input">
                    <span class="form__error">Имя пользователя и пароль не совпадают. Введите правильные данные.
                    </span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_email" class="form__label">Адрес электронной почты</label>
                <div class="form__field-group">
                    <input type="email" name="email" id="id_email" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_password" class="form__label">Пароль</label>
                <div class="form__field-group">
                    <input type="password" name="password" id="id_password" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__footer">
                {% csrf_token %}
                <button class="button button_style_blue">Создать аккаунт</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/shopList_item.html
{% load static %}
{% load thumbnail %}
{% for item in cart %}
<li class="shopping-list__item" data-id={{ item.id }}>
    <div class="recipe recipe_reverse">
        {% thumbnail item.image "50x50" crop="center" upscale=True as im %}
            <img src="{{ im.url }}" class="recipe__image">
        {% endthumbnail %}
        <h3 class="recipe__title">"{{ item.title }}"</h3>
        <p class="recipe__text"><span class="icon-time"></span> {{ item.cooking_duration }} мин. </p>
    </div>
    {% csrf_token %}
    <a href="#" class="shopping-list__button link">Удалить</a>
</li>
{% endfor %}

templates/singlePage.html
{% extends "indexAuth.html" %}
{% load static %}
{% load user_filters %}
{% load thumbnail %}
	{% block title %}{{ recipe.title }}{% endblock %}
	{% block style %}"{% static 'pages/single.css' %}"{% endblock %}
	{% block content %}
        <div class="single-card" data-id={{ recipe.id }} data-author={{ recipe.author.id }}>
            {% thumbnail recipe.image "450x450" crop="center" upscale=True as im %}
            <a href="{{ recipe.image.url }}" class="link">{% if recipe.image %}<img src="{{ im.url }}">
            {% endif %}</a>
            {% endthumbnail %}
            <div class="single-card__info">
                <div class="single-card__header-info">
                    <h1 class="single-card__title">{{ recipe.title }}</h1>
                    <div class="single-card__favorite">
						<button class="button button_style_none" name="favorites" 
						{% if recipe.id|is_favorite:request.user %}><span class="icon-favorite  icon-favorite_active"></span>
						{% else %}data-out><span class="icon-favorite icon-favorite_big"></span>{% endif %}</button>
                    </div>
                </div>
                <ul class="single-card__items">
                    {% include "tags.html" with tags=recipe.taglist %} 
                </ul>
                <div class="single-card__items single-card__items_column">
                    <p class="single-card__text"><span class="icon-time"></span> {{ recipe.cooking_duration}} мин.</p>
                    <ul class="single-card__items">
                        <li class="single-card__item"><p class="single-card__text"><span class="icon-user"></span>{{ recipe.author.username }}</p></li>
                        {% if request.user == recipe.author%}
                        <li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'recipes:recipe_change' recipe.id %}" class="single-card__text">Редактировать рецепт</a></li>
                        {% endif %}
                    </ul>
                </div>
                <ul class="single-card__items">
                    {% csrf_token %}
                    <li class="single-card__item"><button class="button button_style_blue" name="purchases" {% if recipe.id not in cart_ids %}data-out><span class="icon-plus button__icon"></span>Добавить в покупки
						{% else %}><span class="icon-check button__icon"></span>Рецепт добавлен{% endif %}</button></li>
                    <li class="single-card__item"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" {% if not recipe.author|is_follow:request.user %}data-out>Подписаться на автора{% else %}>Отписаться от автора{% endif %}</button></li>					
				</ul>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Ингридиенты:</h3>
                    <div class="single-card__items single-card__items_column">
                        {% for item in recipe.ingredientlist %}
                        <p class=" single-card__section-item">{{ item.ingredient.name }} {{item.quantity}} {{item.ingredient.units}}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Описание:</h3>
                    <p class=" single-card__section-text">{{ recipe.description }}</p>
                    
                </div>
            </div>
		</div>
		{% endblock %}
		{% block script %}
<script src="{% static '/js/components/Purchases.js' %}"></script>
<script src="{% static '/js/components/Favorites.js' %}"></script>
<script src="{% static '/js/components/Subscribe.js' %}"></script>
<script src="{% static '/js/config/config.js' %}"></script>

<script src="{% static '/js/components/MainCards.js' %}"></script>
<script src="{% static '/js/components/SingleCard.js' %}"></script>
<script src="{% static '/js/components/Header.js' %}"></script>

<script src="{% static '/js/api/Api.js' %}"></script>
<script src="{% static 'singlePage.js' %}"></script>
{% endblock %}

templates/tags.html
{% for item in tags %}
<li class="card__item"><span class="badge badge_style_{{ item.style }}">{{ item.tag_name }}</span></li>
{% endfor %}